=== TheAncientOwl/book-of-frets/src/configs/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema | v0.1.1",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "0.1.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "songSegments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string", "enum": ["chords", "strings"] },
          "patterns": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "times": {
                  "type": "integer",
                  "minimum": 1
                },
                "segments": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "chordIDs": {
                            "type": "array",
                            "items": { "type": "string" },
                            "minItems": 1
                          },
                          "chordTimes": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 1
                          },
                          "strummingPattern": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "enum": ["D", "U", "-", "Dx", "Ux"]
                            },
                            "minItems": 1
                          }
                        },
                        "required": ["chordIDs", "chordTimes", "strummingPattern"]
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "string": { "type": "integer", "minimum": 1, "maximum": 6 },
                            "fret": {
                              "anyOf": [
                                { "type": "integer", "minimum": 0, "maximum": 22 },
                                { "type": "string", "enum": ["-"] }
                              ]
                            }
                          },
                          "required": ["string", "fret"]
                        }
                      }
                    ]
                  }
                }
              },
              "required": ["times", "segments"]
            }
          }
        },
        "required": ["name", "type", "patterns"]
      }
    },
    "songSegmentsOrder": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "songSegments",
    "songSegmentsOrder",
    "resources"
  ]
}

=== TheAncientOwl/book-of-frets/songs/without-you/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Without You",
  "artists": ["The Kid LAROI"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Am", "Fmaj7", "C", "G", "E"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["-"],
              "chordTimes": 1,
              "strummingPattern": ["Dx", "-", "Dx", "-", "Dx", "-", "Dx", "Ux"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "chorus1": {
      "name": "chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "pre-chorus1": {
      "name": "pre-chorus 1",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["E"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "-",
                "-",
                "Dx",
                "Ux",
                "Dx",
                "Ux"
              ]
            }
          ]
        }
      ]
    },
    "chorus2": {
      "name": "chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "pre-chorus2": {
      "name": "pre-chorus 2",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "-",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["-"],
              "chordTimes": 1,
              "strummingPattern": [
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "-",
                "Dx",
                "Ux",
                "Dx",
                "Ux"
              ]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am", "Fmaj7", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "chorus1",
    "verse",
    "pre-chorus1",
    "chorus2",
    "bridge",
    "pre-chorus2",
    "chorus1",
    "outro"
  ],
  "resources": [
    {
      "alias": "Without You Guitar Tutorial The Kid LAROI Lesson |Easy Chords + Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/I8UfGA0qR7A"
    },
    {
      "alias": "Without You Guitar Cover The Kid LAROI ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/ayhT2swtB0w"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/never-gonna-give-you-up/config.json
{
  "version": "0.1.1",
  "contributors": ["TheAncientOwl"],
  "title": "Never Gonna Give You Up",
  "artists": ["Rick Astley"],
  "type": ["acoustic"],
  "notes": ["Last chorus Em & Am only one down strum"],
  "capo": 1,
  "chordIDs": ["Fmaj7", "G", "Em", "Am"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 4,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Fmaj7"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D"]
            },
            {
              "chordIDs": ["Am"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Fmaj7", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "-", "D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus": {
      "name": "pre-chorus",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Fmaj7", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "-", "D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 4,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Fmaj7"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D"]
            },
            {
              "chordIDs": ["Am"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "U", "D", "D", "D", "U"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["intro", "verse", "pre-chorus", "chorus", "pre-chorus", "chorus"],
  "resources": [
    {
      "alias": "Rick Astley - Never Gonna Give You Up EASY Guitar Tutorial With Chords / Lyrics",
      "author": "Easy 2 Play Music ~ YouTube",
      "link": "https://youtu.be/iA4mbi7W_xQ"
    },
    {
      "alias": "Never Gonna Give You Up by Rick Astley Guitar Tutorial Lesson!",
      "author": "Chevans Music ~ YouTube",
      "link": "https://www.youtube.com/shorts/EwtfzXa-9k8?feature=share"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/sweater-weather/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Sweater Weather",
  "artists": ["The Neighbourhood"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 3,
  "chordIDs": ["C", "Am", "Em", "G", "D"],
  "songSegments": {
    "verse": {
      "name": "verse",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["Am", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus": {
      "name": "pre-chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 3,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus2": {
      "name": "chorus 2",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Am", "G", "D", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Am", "G", "D", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus3": {
      "name": "chorus 3",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "fade": {
      "name": "fade",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse",
    "pre-chorus",
    "chorus",
    "verse",
    "pre-chorus",
    "chorus2",
    "bridge",
    "chorus3",
    "fade"
  ],
  "resources": [
    {
      "alias": "Sweater Weather Guitar Tutorial - The Neighbourhood Guitar Lesson |Chords + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=kvGorssKuO8"
    },
    {
      "alias": "Sweater Weather Guitar Cover Acoustic - The Neighborhood + Onscreen Chords",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/HcCzuFIOKFw"
    }
  ]
}

=== TheAncientOwl/book-of-frets/src/configs/songs/flowers-need-rain.json
{
  "version": "0.1.1",
  "contributors": ["TheAncientOwl"],
  "title": "Flowers Need Rain",
  "artists": ["Preston Pablo"],
  "type": ["acoustic", "electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["-"],
  "songSegments": {
    "main": {
      "name": "main",
      "type": "strings",
      "patterns": [
        {
          "times": 404,
          "segments": [
            [
              { "string": 1, "fret": 9 },
              { "string": 2, "fret": 9 }
            ],
            [
              { "string": 1, "fret": 9 },
              { "string": 2, "fret": 9 }
            ],
            [
              { "string": 1, "fret": 9 },
              { "string": 2, "fret": 9 }
            ],
            [
              { "string": 1, "fret": 9 },
              { "string": 2, "fret": 9 }
            ],
            [{ "string": 1, "fret": "-" }],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 6 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 6 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 6 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 6 }
            ],
            [{ "string": 1, "fret": "-" }],
            [
              { "string": 1, "fret": 12 },
              { "string": 2, "fret": 13 }
            ],
            [
              { "string": 1, "fret": 12 },
              { "string": 2, "fret": 13 }
            ],
            [
              { "string": 1, "fret": 12 },
              { "string": 2, "fret": 13 }
            ],
            [
              { "string": 1, "fret": 12 },
              { "string": 2, "fret": 13 }
            ],
            [{ "string": 1, "fret": "-" }],
            [
              { "string": 1, "fret": 7 },
              { "string": 2, "fret": 8 }
            ],
            [
              { "string": 1, "fret": 7 },
              { "string": 2, "fret": 8 }
            ],
            [
              { "string": 1, "fret": 7 },
              { "string": 2, "fret": 8 }
            ],
            [
              { "string": 1, "fret": 7 },
              { "string": 2, "fret": 8 }
            ],
            [{ "string": 1, "fret": "-" }]
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main"],
  "resources": [
    {
      "alias": "How to play Flowers Need Rain by Preston Pablo",
      "author": "Elijah Plays ~ YouTube",
      "link": "https://youtu.be/Bl4FiG65g1A"
    }
  ]
}
