=== TheAncientOwl/book-of-frets/src/configs/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema | v0.1.1",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "0.1.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "songSegments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string", "enum": ["chords", "strings"] },
          "patterns": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "times": {
                  "type": "integer",
                  "minimum": 1
                },
                "segments": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "chordIDs": {
                            "type": "array",
                            "items": { "type": "string" },
                            "minItems": 1
                          },
                          "chordTimes": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 1
                          },
                          "strummingPattern": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "enum": ["D", "U", "-", "Dx", "Ux"]
                            },
                            "minItems": 1
                          }
                        },
                        "required": ["chordIDs", "chordTimes", "strummingPattern"]
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "string": { "type": "integer", "minimum": 1, "maximum": 6 },
                            "fret": {
                              "anyOf": [
                                { "type": "integer", "minimum": 0, "maximum": 22 },
                                { "type": "string", "enum": ["-"] }
                              ]
                            }
                          },
                          "required": ["string", "fret"]
                        }
                      }
                    ]
                  }
                }
              },
              "required": ["times", "segments"]
            }
          }
        },
        "required": ["name", "type", "patterns"]
      }
    },
    "songSegmentsOrder": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "songSegments",
    "songSegmentsOrder",
    "resources"
  ]
}

=== TheAncientOwl/book-of-frets/songs/adore-you/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Adore You",
  "artists": ["Harry Styles"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 3,
  "chordIDs": ["Am7", "C", "Fmaj7", "G"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am7", "-", "C", "-"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": ["Fmaj7", "-", "-", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "main-progression-1": {
      "name": "main progression",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 6,
          "segments": [
            {
              "chordIDs": ["Am7", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Fmaj7"],
              "chordTimes": 3,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus-1": {
      "name": "post chorus 1",
      "type": "strings",
      "times": 1,
      "patterns": []
    },
    "main-progression-2": {
      "name": "main progression",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 5,
          "segments": [
            {
              "chordIDs": ["Am7", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Fmaj7"],
              "chordTimes": 3,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus-2": {
      "name": "post chorus 2",
      "type": "strings",
      "times": 1,
      "patterns": []
    },
    "solo": {
      "name": "solo",
      "type": "strings",
      "times": 1,
      "patterns": []
    },
    "main-progression-3": {
      "name": "main progression",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Am7", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Fmaj7"],
              "chordTimes": 3,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus-3": {
      "name": "post chorus 2",
      "type": "strings",
      "times": 1,
      "patterns": []
    }
  },
  "songSegmentsOrder": [
    "intro",
    "main-progression-1",
    "post-chorus-1",
    "main-progression-2",
    "post-chorus-2",
    "solo",
    "main-progression-3",
    "post-chorus-3"
  ],
  "resources": [
    {
      "alias": "Adore You Guitar Cover Harry Styles ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/qkmwTHcuoig"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/run-away-to-mars/config.json
{
  "version": "0.1.1",
  "contributors": ["TheAncientOwl"],
  "title": "Run Away To Mars",
  "artists": ["TALK"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["G", "D/F#", "Em7", "Cadd9", "Am7", "D", "Dsus4"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["G", "D/F#", "Em7", "Cadd9"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["G", "D/F#", "Em7", "Cadd9"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus": {
      "name": "pre-chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Am7", "D"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D"]
            },
            {
              "chordIDs": ["D/F#"],
              "chordTimes": 2,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Am7", "Dsus4", "D"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "patterns": [
        {
          "times": 3,
          "segments": [
            {
              "chordIDs": ["Em", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["D/F#", "Em", "C", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "verse",
    "pre-chorus",
    "chorus",
    "verse",
    "pre-chorus",
    "chorus",
    "bridge",
    "outro"
  ],
  "resources": [
    {
      "alias": "Run Away to Mars by TALK - Beginner Guitar Lesson & Play Along",
      "author": "Mechanics Of Music",
      "link": "https://youtu.be/tagR628ZDMY"
    }
  ]
}

=== TheAncientOwl/book-of-frets/src/configs/songs/nice-to-meet-you.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Nice to Meet You",
  "artists": ["Myles Smith"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["Em", "C", "G", "D"],
  "songSegments": {
    "verse": {
      "name": "verse",
      "type": "chords",
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["G"],
              "chordTimes": 4,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus": {
      "name": "pre-chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["C"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["G"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["Em", "C", "G", "D"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus": {
      "name": "post-chorus",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em", "C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Em", "C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse",
    "pre-chorus",
    "chorus",
    "verse",
    "pre-chorus",
    "chorus",
    "post-chorus"
  ],
  "resources": [
    {
      "alias": "Myles Smith - Nice To Meet You EASY Guitar Tutorial With Chords / Lyrics",
      "author": "Easy 2 Play Music ~ YouTube",
      "link": "https://youtu.be/kh2a-4aH5J8"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/golden-acoustic-v1/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Golden",
  "artists": ["HUNTR/X"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["C", "G", "D", "Em", "Bm"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "verse-1": {
      "name": "verse 1",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 4,
          "segments": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus-1": {
      "name": "pre-chorus 1",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 3,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse-2": {
      "name": "verse 2",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["Bm", "C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["Bm", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus-2": {
      "name": "pre-chorus 2",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["Em", "D", "Bm", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["D", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus": {
      "name": "post chorus",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 1,
          "segments": [
            {
              "chordIDs": ["C", "D", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "times": 1,
      "patterns": [
        {
          "times": 2,
          "segments": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "verse-1",
    "pre-chorus-1",
    "chorus",
    "verse-2",
    "pre-chorus-2",
    "chorus",
    "post-chorus",
    "outro"
  ],
  "resources": [
    {
      "alias": "Golden - Huntrix (KPop Demon Hunters) EASY Guitar Tutorial with Chords | Lyrics",
      "author": "Kaan Arkin Guitar ~ YouTube",
      "link": "https://youtu.be/C9YBcVx0qE4"
    }
  ]
}

=== TheAncientOwl/book-of-frets/src/configs/songs/seven-nation-army.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Seven Nation Army",
  "artists": ["The White Stripes"],
  "type": ["acoustic", "electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["-"],
  "songSegments": {
    "main1": {
      "name": "main 1",
      "type": "strings",
      "patterns": [
        {
          "times": 3,
          "segments": [
            [{ "string": 1, "fret": 7 }],
            [{ "string": 1, "fret": 7 }],
            [{ "string": 1, "fret": 10 }],
            [{ "string": 1, "fret": 7 }],
            [{ "string": 1, "fret": 5 }],
            [{ "string": 1, "fret": 3 }],
            [{ "string": 1, "fret": 2 }]
          ]
        }
      ]
    },
    "main2": {
      "name": "main 2",
      "type": "strings",
      "patterns": [
        {
          "times": 1,
          "segments": [
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 3 },
              { "string": 2, "fret": 5 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ],
            [
              { "string": 1, "fret": 5 },
              { "string": 2, "fret": 7 }
            ]
          ]
        }
      ]
    },
    "main3": {
      "name": "main 3",
      "type": "strings",
      "patterns": [
        {
          "times": 1,
          "segments": [
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 10 },
              { "string": 3, "fret": 12 }
            ],
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 5 },
              { "string": 3, "fret": 7 }
            ],
            [
              { "string": 2, "fret": 3 },
              { "string": 3, "fret": 5 }
            ],
            [
              { "string": 2, "fret": 2 },
              { "string": 3, "fret": 4 }
            ]
          ]
        },
        {
          "times": 1,
          "segments": [
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 10 },
              { "string": 3, "fret": 12 }
            ],
            [
              { "string": 2, "fret": 7 },
              { "string": 3, "fret": 9 }
            ],
            [
              { "string": 2, "fret": 5 },
              { "string": 3, "fret": 7 }
            ],
            [
              { "string": 2, "fret": 3 },
              { "string": 3, "fret": 5 }
            ],
            [
              { "string": 2, "fret": 5 },
              { "string": 3, "fret": 7 }
            ],
            [
              { "string": 2, "fret": 3 },
              { "string": 3, "fret": 5 }
            ],
            [
              { "string": 2, "fret": 2 },
              { "string": 3, "fret": 4 }
            ]
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "strings",
      "patterns": [
        {
          "times": 1,
          "segments": [
            [{ "string": 2, "fret": 7 }],
            [{ "string": 2, "fret": 7 }],
            [{ "string": 2, "fret": 10 }],
            [{ "string": 2, "fret": 7 }],
            [{ "string": 2, "fret": 5 }],
            [{ "string": 2, "fret": 3 }],
            [{ "string": 2, "fret": 2 }]
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main1", "main2", "main3", "main3", "main2", "outro"],
  "resources": [
    {
      "alias": "The White Stripes - Seven Nation Army | Riff Tabs | Guitar Lesson/Tutorial | Acoustic Riff: 12",
      "author": "Acoustic Version ~ YouTube",
      "link": "https://youtu.be/eTY4FLGObHo"
    }
  ]
}
