=== TheAncientOwl/book-of-frets/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "0.1.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "songSegments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string", "enum": ["chords", "strings", "tabs"] },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "chunks": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "times": {
                  "type": "integer",
                  "minimum": 1
                },
                "items": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "align": {
                            "type": "string",
                            "enum": ["center", "flex-start", "flex-end"]
                          },
                          "chordIDs": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": { "type": "string" },
                              "minItems": 1
                            },
                            "minItems": 1
                          },
                          "chordTimes": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 1
                          },
                          "strummingPattern": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue"]
                            },
                            "minItems": 1
                          }
                        },
                        "required": ["chordIDs", "chordTimes", "strummingPattern"]
                      },
                      {
                        "oneOf": [
                          {
                            "type": "string",
                            "enum": ["-", "|"]
                          },
                          {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "E": { "type": ["integer", "string"], "minimum": 0 },
                              "A": { "type": ["integer", "string"], "minimum": 0 },
                              "D": { "type": ["integer", "string"], "minimum": 0 },
                              "G": { "type": ["integer", "string"], "minimum": 0 },
                              "B": { "type": ["integer", "string"], "minimum": 0 },
                              "e": { "type": ["integer", "string"], "minimum": 0 }
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "required": ["times", "items"]
            }
          }
        },
        "required": ["name", "type", "times", "chunks"]
      }
    },
    "songSegmentsOrder": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "songSegments",
    "songSegmentsOrder",
    "resources"
  ]
}

=== TheAncientOwl/book-of-frets/songs/dusk-till-dawn/config.json
{
  "version": "0.2.0",
  "contributors": ["TheAncientOwl"],
  "title": "Dusk Till Dawn",
  "artists": ["Zayn", "Sia"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "Fmaj7", "C", "G/B", "Em", "C/E"],
  "songSegments": {
    "verse/prechorus-intro": {
      "name": "verse / prechorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "G/B"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "G/B"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "D", "D", "D", "De", "D", "D", "D"]
            }
          ]
        },
        {
          "times": 2,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "G/B"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Am"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "-", "-", "D", "-", "D", "U"]
            }
          ]
        },
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "Em"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "break": {
      "name": "break",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Am"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "verse/prechorus": {
      "name": "verse / prechorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "G/B"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "D", "D", "D", "De", "D", "D", "D"]
            }
          ]
        },
        {
          "times": 2,
          "items": [
            {
              "chordIDs": [["Am", "Fmaj7", "C", "G/B"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Fmaj7"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["Fmaj7", "C"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["C", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["G", "C/E"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Fmaj7"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["Fmaj7", "C"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["C", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse/prechorus-intro",
    "chorus",
    "break",
    "verse/prechorus",
    "chorus",
    "bridge",
    "chorus"
  ],
  "resources": [
    {
      "alias": "Dusk Till Dawn Guitar Tutorial - Zayn feat Sia Guitar Lesson ðŸŽ¸ |Chords + No Capo + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/v2AMU6dh0pA"
    },
    {
      "alias": "Dusk Till Dawn Guitar Cover Acoustic - Zayn Feat Sia ðŸŽ¸ |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/qT8s6mvDzxw"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/sweater-weather/config.json
{
  "version": "0.4.0",
  "contributors": ["TheAncientOwl"],
  "title": "Sweater Weather",
  "artists": ["The Neighbourhood"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 3,
  "chordIDs": ["C", "Am", "Em", "G", "D"],
  "songSegments": {
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            },
            {
              "chordIDs": [["Am", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus": {
      "name": "pre-chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus2": {
      "name": "chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["D"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": [["Am", "G", "D", "D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["Am", "G", "D", "D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus3": {
      "name": "chorus 3",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": [["C", "Am", "Em", "G"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse",
    "pre-chorus",
    "chorus",
    "verse",
    "pre-chorus",
    "chorus2",
    "bridge",
    "chorus3",
    "outro"
  ],
  "resources": [
    {
      "alias": "Sweater Weather Guitar Tutorial - The Neighbourhood Guitar Lesson |Chords + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=kvGorssKuO8"
    },
    {
      "alias": "Sweater Weather Guitar Cover Acoustic - The Neighborhood + Onscreen Chords",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/HcCzuFIOKFw"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/radioactive/config.json
{
  "version": "0.4.0",
  "contributors": ["TheAncientOwl"],
  "title": "Radioactive",
  "artists": ["Imagine Dragons"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "C", "G", "D"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["Am", "C", "G", "D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["Am", "C", "G", "D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U", "D", "-", "D", "U"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["intro", "verse"],
  "resources": [
    {
      "alias": "Radioactive Guitar Tutorial - Imagine Dragons Guitar Lesson |Easy Chords + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=l2KR3vvgqB0"
    },
    {
      "alias": "Radioactive Guitar Cover Acoustic - Imagine Dragons ðŸŽ¸ |Guitar Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/wQKXwxXvMMA"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/golden-acoustic-v1/config.json
{
  "version": "0.2.1",
  "contributors": ["TheAncientOwl"],
  "title": "Golden",
  "artists": ["HUNTR/X"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["C", "G", "D", "Em", "Bm"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "verse-1": {
      "name": "verse 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus-1": {
      "name": "pre-chorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["D", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-1": {
      "name": "chorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 3,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse-2": {
      "name": "verse 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["D", "Bm", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["D", "Bm", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "pre-chorus-2": {
      "name": "pre-chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Em", "D", "Bm", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Em", "Bm", "D", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-2": {
      "name": "chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em", "C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus": {
      "name": "post chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": ["C", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": ["C", "G", "D", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["C", "G", "D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "U", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "verse-1",
    "pre-chorus-1",
    "chorus-1",
    "verse-2",
    "pre-chorus-2",
    "chorus-2",
    "post-chorus",
    "outro"
  ],
  "resources": [
    {
      "alias": "Golden - Huntrix (KPop Demon Hunters) EASY Guitar Tutorial with Chords | Lyrics",
      "author": "Kaan Arkin Guitar ~ YouTube",
      "link": "https://youtu.be/C9YBcVx0qE4"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/flowers-need-rain/config.json
{
  "version": "0.4.0",
  "contributors": ["TheAncientOwl"],
  "title": "Flowers Need Rain",
  "artists": ["Preston Pablo"],
  "type": ["acoustic", "electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["-"],
  "songSegments": {
    "main": {
      "name": "main",
      "type": "strings",
      "times": 1,
      "chunks": [
        {
          "times": 404,
          "items": [
            "-",
            { "E": 9, "A": 9 },
            { "E": 9, "A": 9 },
            { "E": 9, "A": 9 },
            { "E": 9, "A": 9 },
            "-",
            { "E": 6, "A": 6 },
            { "E": 6, "A": 6 },
            { "E": 6, "A": 6 },
            { "E": 6, "A": 6 },
            "-",
            { "E": 12, "A": 13 },
            { "E": 12, "A": 13 },
            { "E": 12, "A": 13 },
            { "E": 12, "A": 13 },
            "-",
            { "E": 7, "A": 8 },
            { "E": 7, "A": 8 },
            { "E": 7, "A": 8 },
            { "E": 7, "A": 8 },
            {}
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main"],
  "resources": [
    {
      "alias": "How to play Flowers Need Rain by Preston Pablo",
      "author": "Elijah Plays ~ YouTube",
      "link": "https://youtu.be/Bl4FiG65g1A"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/shivers/config.json
{
  "version": "0.2.0",
  "contributors": ["TheAncientOwl"],
  "title": "Shivers",
  "artists": ["Ed Sheeran"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Bm", "G", "D", "A"],
  "songSegments": {
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": [["Bm", "G", "D", "A"]],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "Ue",
                "-",
                "U",
                "D",
                "Ue",
                "-",
                "U",
                "D",
                "Ue",
                "-",
                "U",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    },
    "chorus-1": {
      "name": "chorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": [["Bm", "G", "D"]],
              "chordTimes": 2,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            },
            {
              "chordIDs": [["A"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Bm", "G", "D", "A"]],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "U",
                "D",
                "U",
                "-",
                "U",
                "D",
                "U",
                "-",
                "U",
                "D",
                "U",
                "-",
                "U",
                "D",
                "U"
              ]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Bm", "G", "D", "A"]],
              "chordTimes": 4,
              "strummingPattern": ["D", "U", "Dx", "U"]
            }
          ]
        }
      ]
    },
    "chorus-2": {
      "name": "chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Bm"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            },
            {
              "chordIDs": [["G", "D"]],
              "chordTimes": 2,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            },
            {
              "chordIDs": [["A"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Bm", "G", "D"]],
              "chordTimes": 2,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            },
            {
              "chordIDs": [["A"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "Dx", "Ux", "-", "Ux", "Dx", "Ux"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["verse", "chorus-1", "verse", "chorus-2"],
  "resources": [
    {
      "alias": "Shivers Guitar Tutorial Ed Sheeran Guitar Lesson |No Capo + Easy Chords|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/fxP2CM4QoiU"
    },
    {
      "alias": "Shivers Guitar Cover Ed Sheeran ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/jUo76Aawb3c"
    }
  ]
}
