=== TheAncientOwl/book-of-frets/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "0.1.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "songSegments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string", "enum": ["chords", "strings", "tabs"] },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "chunks": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "times": {
                  "type": "integer",
                  "minimum": 1
                },
                "items": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "align": {
                            "type": "string",
                            "enum": ["center", "flex-start", "flex-end"]
                          },
                          "chordIDs": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": { "type": "string" },
                              "minItems": 1
                            },
                            "minItems": 1
                          },
                          "chordTimes": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 1
                          },
                          "strummingPattern": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue"]
                            },
                            "minItems": 1
                          }
                        },
                        "required": ["chordIDs", "chordTimes", "strummingPattern"]
                      },
                      {
                        "oneOf": [
                          {
                            "type": "string",
                            "enum": ["-", "|"]
                          },
                          {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "E": { "type": ["integer", "string"], "minimum": 0 },
                              "A": { "type": ["integer", "string"], "minimum": 0 },
                              "D": { "type": ["integer", "string"], "minimum": 0 },
                              "G": { "type": ["integer", "string"], "minimum": 0 },
                              "B": { "type": ["integer", "string"], "minimum": 0 },
                              "e": { "type": ["integer", "string"], "minimum": 0 }
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "required": ["times", "items"]
            }
          }
        },
        "required": ["name", "type", "times", "chunks"]
      }
    },
    "songSegmentsOrder": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "songSegments",
    "songSegmentsOrder",
    "resources"
  ]
}

=== TheAncientOwl/book-of-frets/songs/watermelon-sugar/config.json
{
  "version": "0.4.0",
  "contributors": ["TheAncientOwl"],
  "title": "Watermelon Sugar",
  "artists": ["Harry Styles"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Dm", "Am", "C", "G"],
  "songSegments": {
    "main": {
      "name": "main",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 404,
          "items": [
            {
              "chordIDs": [["Dm", "Am", "C", "G"]],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "-",
                "D",
                "-",
                "D",
                "U",
                "-",
                "U",
                "D",
                "U",
                "-",
                "U",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main"],
  "resources": [
    {
      "alias": "Watermelon Sugar Guitar Tutorial üçâ Harry Styles Guitar Lesson |Easy Chords + No Capo|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/l9gEAU3Mzp8"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/viva-la-vida/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Viva La Vida",
  "artists": ["Coldplay"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["C", "D", "G", "Em"],
  "songSegments": {
    "verse-palm-muted": {
      "name": "verse palm muted",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "De", "D", "De", "D", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["De", "D", "De", "D", "D", "De", "D", "De", "D"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "De", "D", "De", "D", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["De", "D", "De", "D", "D", "De", "D", "De", "D"]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 8,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-1": {
      "name": "chorus",
      "type": "chords",
      "times": 4,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-2": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "build-up": {
      "name": "build up",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-3": {
      "name": "chorus",
      "type": "chords",
      "times": 5,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "D", "G", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse-palm-muted",
    "verse",
    "chorus-1",
    "verse",
    "chorus-2",
    "build-up",
    "chorus-3",
    "outro"
  ],
  "resources": [
    {
      "alias": "Viva La Vida Guitar Tutorial ðŸŽ¸ Coldplay Guitar Lesson |Easy + Live Version Chords + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=EgnNfb4f2TU"
    },
    {
      "alias": "Viva La Vida Guitar Cover Coldplay ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/lhR434nrXK4"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/jingle-bell-rock/config.json
{
  "version": "0.2.0",
  "contributors": ["TheAncientOwl"],
  "title": "Jingle Bell Rock",
  "artists": ["Bobby Helms"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["D", "DM7", "D6", "D#dim7", "Em7", "A7", "D7", "G#dim7", "E7", "A", "G", "Gm"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "strings",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            "|",
            "-",
            { "G": 7, "B": 7 },
            "-",
            { "G": 7, "B": 7 },
            "-",
            { "G": 7, "B": 7 },
            "-",
            "-",
            "-",
            { "G": 6, "B": 7 },
            "-",
            { "G": 6, "B": 7 },
            "-",
            { "G": 6, "B": 7 },
            "-",
            "-",
            "-",
            "|",
            "-",
            { "B": 7 },
            "-",
            { "e": 5 },
            "-",
            { "G": 7 },
            "-",
            { "B": 5 },
            "-",
            { "B": 5 },
            { "B": 6 },
            "-",
            { "B": 5 },
            "-",
            { "G": 7 },
            "-",
            { "G": 4 },
            "-",
            "|",
            "-",
            { "D": 7 },
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "|",
            "-",
            "-",
            "-",
            { "E": 5 },
            "-",
            { "E": 3 },
            "-",
            "-",
            "-",
            { "E": 2 },
            "-",
            "-",
            "-",
            { "E": 0 },
            "-",
            "-",
            "-",
            "|"
          ]
        }
      ]
    },
    "verse-1": {
      "name": "verse 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [
                ["D", "DM7", "|", "D6", "D"],
                ["D6", "D#dim7", "|", "Em7", "A7"],
                ["Em7", "A7", "|", "Em7", "A7"],
                ["Em7", "A7"]
              ],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse-2": {
      "name": "verse 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [
                ["D", "DM7", "|", "D6", "D"],
                ["D6", "D#dim7", "|", "Em7", "A7"],
                ["Em7", "A7", "|", "Em7", "A7"],
                ["Em7", "A7", "|", "D", "D7"]
              ],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [
                ["G", "G#dim7", "D", "D"],
                ["E7", "E7"]
              ],
              "chordTimes": 4,
              "strummingPattern": ["D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["A"]],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus-riff": {
      "name": "chorus riff",
      "type": "strings",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            "|",
            "-",
            "-",
            "-",
            { "E": 5 },
            "-",
            { "E": 3 },
            "-",
            "-",
            "-",
            { "E": 2 },
            "-",
            "-",
            "-",
            { "E": 0 },
            "-",
            "-",
            "-",
            "|"
          ]
        }
      ]
    },
    "post-chorus-1": {
      "name": "post chorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [
                ["D", "DM7", "|", "D6", "D"],
                ["D6", "B7"],
                ["G", "Gm"],
                ["Em7", "A7", "D"]
              ],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse-3": {
      "name": "verse 3",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["D", "DM7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            },
            {
              "chordIDs": [["D6", "D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["D6", "D#dim7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            },
            {
              "chordIDs": [["Em7", "A7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Em7", "A7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            },
            {
              "chordIDs": [["Em7", "A7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["Em7", "A7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            },
            {
              "chordIDs": [["D", "D7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "post-chorus-2": {
      "name": "post chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [
                ["D", "DM7", "|", "D6", "D"],
                ["D6", "B7"],
                ["G", "Gm"],
                ["Em7", "A7", "|", "Em7", "A7"],
                ["Em7", "A7", "D"]
              ],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["D"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U", "-", "-", "D", "-"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "verse-1",
    "verse-2",
    "chorus",
    "chorus-riff",
    "post-chorus-1",
    "chorus",
    "chorus-riff",
    "post-chorus-2"
  ],
  "resources": [
    {
      "alias": "Jingle Bell Rock Guitar Tutorial Bobbly Helms Acoustic Guitar Lesson |Chords + Strumming|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/kGE2j5wVs0Q"
    },
    {
      "alias": "Jingle Bell Rock Guitar Cover Bobby Helms ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/zy76BuTfwwE"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/before-you-go/config.min.json
{"version":"0.2.0","contributors":["TheAncientOwl"],"title":"Before You go","artists":["Lewis Capaldi"],"type":["acoustic"],"notes":[],"capo":3,"chordIDs":["C","Am","Fmaj7","G"],"songSegments":{"verse-picked-1":{"name":"verse picked 1","type":"tabs","times":1,"chunks":[]},"chorus-picked":{"name":"chorus picked","type":"tabs","times":1,"chunks":[]},"break":{"name":"chorus picked","type":"tabs","times":1,"chunks":[]},"verse-strummed":{"name":"verse strummed","type":"chords","times":1,"chunks":[{"times":2,"items":[{"chordIDs":[["C","Am","Fmaj7","G"]],"chordTimes":4,"strummingPattern":["D","-","D","U","D","U"]}]}]},"chorus-strummed":{"name":"chorus strummed","type":"chords","times":1,"chunks":[{"times":2,"items":[{"chordIDs":[["C","G","Am","Fmaj7"]],"chordTimes":4,"strummingPattern":["D","-","D","U","D","U"]}]},{"times":1,"items":[{"chordIDs":[["G"]],"chordTimes":1,"strummingPattern":["D","-","D","U","D","U"]}]}]},"bridge":{"name":"Bridge","type":"chords","times":1,"chunks":[{"times":1,"items":[{"chordIDs":[["Am","F","C","G"],["Am","F","G","G"]],"chordTimes":2,"strummingPattern":["D","-","D","U","D","U"]}]}]},"final-chorus-1":{"name":"final chorus","type":"tabs","times":1,"chunks":[]},"final-chorus-2":{"name":"final chorus 2","type":"chords","times":1,"chunks":[{"times":1,"items":[{"chordIDs":[["C","G","Am"]],"chordTimes":4,"strummingPattern":["D","-","D","U","D","U"]},{"chordIDs":[["Fmaj7"]],"chordTimes":3,"strummingPattern":["D","-","D","U","D","U"]}]}]},"verse-picked-2":{"name":"verse picked 2","type":"tabs","times":1,"chunks":[]}},"songSegmentsOrder":["verse-picked-1","chorus-picked","break","verse-strummed","chorus-strummed","bridge","final-chorus-1","final-chorus-2","verse-picked-2"],"resources":[{"alias":"Before You Go Guitar Tutorial ðŸŽ¸ Lewis Capaldi Guitar Lesson |Fingerpicking + TAB|","author":"GuitarZero2Hero ~ YouTube","link":"https://youtu.be/xynOZh5dLEg"},{"alias":"Before You Go Guitar Cover Lewis Capaldi ðŸŽ¸|Tabs + Chords|","author":"GuitarZero2Hero Express ~ YouTube","link":"https://youtu.be/s949Lv3agb8"}]}
