=== TheAncientOwl/book-of-frets/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "0.1.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "songSegments": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string", "enum": ["chords", "strings", "tabs"] },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "chunks": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "times": {
                  "type": "integer",
                  "minimum": 1
                },
                "items": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "align": {
                            "type": "string",
                            "enum": ["center", "flex-start", "flex-end"]
                          },
                          "chordIDs": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": { "type": "string" },
                              "minItems": 1
                            },
                            "minItems": 1
                          },
                          "chordTimes": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 1
                          },
                          "strummingPattern": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue"]
                            },
                            "minItems": 1
                          }
                        },
                        "required": ["chordIDs", "chordTimes", "strummingPattern"]
                      },
                      {
                        "oneOf": [
                          {
                            "type": "string",
                            "enum": ["-", "|"]
                          },
                          {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "E": { "type": ["integer", "string"], "minimum": 0 },
                              "A": { "type": ["integer", "string"], "minimum": 0 },
                              "D": { "type": ["integer", "string"], "minimum": 0 },
                              "G": { "type": ["integer", "string"], "minimum": 0 },
                              "B": { "type": ["integer", "string"], "minimum": 0 },
                              "e": { "type": ["integer", "string"], "minimum": 0 }
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "required": ["times", "items"]
            }
          }
        },
        "required": ["name", "type", "times", "chunks"]
      }
    },
    "songSegmentsOrder": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "songSegments",
    "songSegmentsOrder",
    "resources"
  ]
}

=== TheAncientOwl/book-of-frets/songs/viva-la-vida-easy/config.json
{
  "version": "0.1.1",
  "contributors": ["TheAncientOwl"],
  "title": "Viva La Vida ~ Easy",
  "artists": ["Coldplay"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["C", "D_3fr", "D", "G", "Em"],
  "songSegments": {
    "verse-palm-muted": {
      "name": "verse palm muted",
      "type": "chords",
      "times": 2,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "De", "D", "De", "D", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["De", "D", "De", "D", "D", "De", "D", "De", "D"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "De", "D", "De", "D", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["De", "D", "De", "D", "D", "De", "D", "De", "D"]
            }
          ]
        }
      ]
    },
    "verse-1": {
      "name": "verse",
      "type": "chords",
      "times": 8,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 4,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse-2": {
      "name": "verse",
      "type": "chords",
      "times": 6,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "build-up": {
      "name": "build up",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 3,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus-2": {
      "name": "chorus",
      "type": "chords",
      "times": 5,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["D_3fr"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "U", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 1,
              "strummingPattern": ["U", "-", "U", "D", "U", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "outro": {
      "name": "outro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "D_3fr", "G", "Em"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "verse-palm-muted",
    "verse-1",
    "chorus",
    "verse-2",
    "chorus",
    "build-up",
    "chorus-2",
    "outro"
  ],
  "resources": [
    {
      "alias": "Viva La Vida Guitar Tutorial ðŸŽ¸ Coldplay Guitar Lesson |Easy + Live Version Chords + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=EgnNfb4f2TU"
    },
    {
      "alias": "Viva La Vida Guitar Cover Coldplay ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/lhR434nrXK4"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/wake-me-up/config.json
{
  "version": "0.3.0",
  "contributors": ["TheAncientOwl"],
  "title": "Wake Me Up",
  "artists": ["Avicii"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "Fmaj7", "G", "C/G", "E"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "E"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "chorus": {
      "name": "chorus",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "E"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "dance": {
      "name": "dance",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            },
            {
              "chordIDs": ["C/G", "E"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    },
    "verse": {
      "name": "verse",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Am", "Fmaj7", "C/G", "C/G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "-", "U", "D", "U"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["intro", "chorus", "dance", "verse"],
  "resources": [
    {
      "alias": "Wake Me Up Guitar Tutorial - Avicii Guitar Lesson ðŸŽ¸|100% Accurate Chords + Lead + No Capo + Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=_u4wlBmXGmw&t=202s"
    },
    {
      "alias": "Wake Me Up Guitar Cover Acoustic - Avicii ðŸŽ¸ |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://www.youtube.com/watch?v=ttQ4zKNH3l0"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/riptide/config.min.json
{"version":"0.1.0","contributors":["TheAncientOwl"],"title":"Riptide","artists":["Vance Joy"],"type":["acoustic"],"notes":[],"capo":5,"chordIDs":["Am","G","C","Fmaj7"],"songSegments":{"intro/verse/chorus":{"name":"intro / verse / chorus","type":"chords","times":1,"chunks":[{"times":15,"items":[{"chordIDs":[["Am","G","C","C"]],"chordTimes":1,"strummingPattern":["D","-","D","-","-","U","D","U"]}]}]},"break":{"name":"break","type":"strings","times":4,"chunks":[{"times":1,"items":["|","-",{"B":3},{"B":"h"},{"B":5},"-",{"B":5},{"e":3},"-","-","-","-",{"G":5},"-",{"B":5},"-","-","-","|"]}]},"bridge":{"name":"bridge","type":"chords","times":1,"chunks":[{"times":2,"items":[{"chordIDs":[["Am","G","C","Fmaj7"]],"chordTimes":2,"strummingPattern":["D","-","D","-","-","U","D","U"]}]}]},"post-bridge":{"name":"post bridge","type":"chords","times":1,"chunks":[{"times":2,"items":[{"chordIDs":[["Am","G","C"]],"chordTimes":1,"strummingPattern":["D"]}]}]}},"songSegmentsOrder":["intro/verse/chorus","break","bridge","intro/verse/chorus"],"resources":[{"alias":"Riptide Guitar Tutorial - Vance Joy Guitar Lesson ðŸŽ¸ |Easy Chords + Guitar Cover|","author":"GuitarZero2Hero ~ YouTube","link":"https://youtu.be/no4u0CTAR_Q"},{"alias":"Riptide Guitar Cover Acoustic - Vance Joy ðŸŽ¸ |Chords|","author":"GuitarZero2Hero Express ~ YouTube","link":"https://youtu.be/twmHegxF7Jo"}]}

=== TheAncientOwl/book-of-frets/public/songs/just-the-two-of-us-lvl1/config.json
{
  "version": "0.3.0",
  "contributors": ["TheAncientOwl"],
  "title": "Just the Two of Us | Lvl 1",
  "artists": ["Grover Washington Jr."],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["CM7", "B7", "Em", "Dm7", "G7"],
  "songSegments": {
    "main-progression": {
      "name": "main progression",
      "type": "chords",
      "times": 404,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["CM7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            },
            {
              "chordIDs": [["B7"]],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": [["Em"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            },
            {
              "chordIDs": [["Dm7", "G7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": [["CM7"]],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "U", "-", "U", "D", "U"]
            },
            {
              "chordIDs": [["B7"]],
              "chordTimes": 2,
              "strummingPattern": ["D", "-", "D", "U"]
            },
            {
              "chordIDs": [["Em"]],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "-",
                "U",
                "D",
                "U",
                "D",
                "-",
                "-",
                "U",
                "D",
                "U",
                "D",
                "-",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main-progression"],
  "resources": [
    {
      "alias": "Just The Two Of Us Guitar Tutorial Grover Washington Jr Guitar |Chords + Fingerpicking|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/mBEtlbfCzj0"
    },
    {
      "alias": "Just The Two Of Us Guitar Cover Grover Washington Jr ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/E65OP4e2bwU"
    },
    {
      "alias": "Book Of Frets ~ Just the Two of Us | Lvl 1",
      "author": "-",
      "link": "{book-of-frets}#/just-the-two-of-us-lvl1"
    },
    {
      "alias": "Book Of Frets ~ Just the Two of Us | Lvl 2",
      "author": "-",
      "link": "{book-of-frets}#/just-the-two-of-us-lvl2"
    }
  ]
}

=== TheAncientOwl/book-of-frets/public/songs/as-it-was/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "As It Was",
  "artists": ["Harry Styles"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Dsus2", "Bm7", "E", "A"],
  "songSegments": {
    "main-progression": {
      "name": "main progression",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 404,
          "items": [
            {
              "chordIDs": ["Dsus2", "Bm7", "E", "A"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "D",
                "U",
                "D",
                "U",
                "-",
                "U",
                "D",
                "-",
                "D",
                "U",
                "D",
                "U"
              ]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": ["main-progression"],
  "resources": [
    {
      "alias": "As It Was Guitar Tutorial - Harry Styles Guitar Lesson |Chords + Fingerpicking|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/I-k5YIgPJCM"
    },
    {
      "alias": "As It Was Guitar Cover Harry Styles ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/oLeG9U-6UO8"
    }
  ]
}

=== TheAncientOwl/book-of-frets/songs/save-your-tears/config.json
{
  "version": "0.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Save Your Tears",
  "artists": ["The Weekend", "Ariana Grande"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["C", "Am", "Em", "G", "Fmaj7"],
  "songSegments": {
    "intro": {
      "name": "intro",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C"],
              "chordTimes": 4,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        }
      ]
    },
    "verse-1": {
      "name": "verse 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 8,
          "items": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        }
      ]
    },
    "prechorus-1": {
      "name": "prechorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Dm", "Am", "Fmaj7", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        }
      ]
    },
    "chorus-1": {
      "name": "chorus 1",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "Am"],
              "chordTimes": 1,
              "strummingPattern": ["D", "D"]
            },
            {
              "chordIDs": ["Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U", "D", "U", "D", "U"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["C", "Am"],
              "chordTimes": 1,
              "strummingPattern": ["D", "D"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 4,
              "strummingPattern": ["D", "U", "D", "U", "D", "U", "D", "U"]
            },
            {
              "chordIDs": ["Em"],
              "chordTimes": 4,
              "strummingPattern": ["D", "U", "D", "U", "D", "-", "-", "-"]
            }
          ]
        }
      ]
    },
    "verse-2": {
      "name": "verse 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        }
      ]
    },
    "prechorus-2": {
      "name": "prechorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Dm", "Am", "Fmaj7"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["F", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "-", "D", "-", "D", "-", "D", "-"]
            }
          ]
        },
        {
          "times": 1,
          "items": [
            {
              "chordIDs": ["Dm", "Am", "Fmaj7", "G"],
              "chordTimes": 1,
              "strummingPattern": [
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-",
                "D",
                "-",
                "D",
                "-",
                "De",
                "-",
                "D",
                "-"
              ]
            }
          ]
        }
      ]
    },
    "bridge": {
      "name": "bridge",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 2,
          "items": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D"]
            }
          ]
        }
      ]
    },
    "chorus-2": {
      "name": "chorus 2",
      "type": "chords",
      "times": 1,
      "chunks": [
        {
          "times": 4,
          "items": [
            {
              "chordIDs": ["C", "Am", "Em", "G"],
              "chordTimes": 1,
              "strummingPattern": ["D", "U", "D", "U", "D", "U", "D", "U"]
            }
          ]
        }
      ]
    }
  },
  "songSegmentsOrder": [
    "intro",
    "verse-1",
    "prechorus-1",
    "chorus-1",
    "verse-2",
    "prechorus-2",
    "chorus-1",
    "bridge",
    "chorus-2"
  ],
  "resources": [
    {
      "alias": "Save Your Tears Guitar Tutorial The Weeknd Guitar Lesson |Easy Chords|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/aPuujELV4Hg"
    },
    {
      "alias": "Save Your Tears Guitar Cover The Weeknd ðŸŽ¸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/NF-gjc8-fz0?"
    }
  ]
}
